// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeMpPgX_ZAVDJRL9e4Jf2dsB3lJJZuvh4',
    appId: '1:978035655325:web:618af299573645cea54a74',
    messagingSenderId: '978035655325',
    projectId: 'cooking-daddy-83353',
    authDomain: 'cooking-daddy-83353.firebaseapp.com',
    storageBucket: 'cooking-daddy-83353.firebasestorage.app',
    measurementId: 'G-0CV6XF32XD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoL9ZYVpYLYaCfHGGNz8gQtXZnUr0CG7I',
    appId: '1:978035655325:android:21abafa26f7ad3e0a54a74',
    messagingSenderId: '978035655325',
    projectId: 'cooking-daddy-83353',
    storageBucket: 'cooking-daddy-83353.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt8fOz6t2iHzHUOmCCxDwwh0pAIAeuVk4',
    appId: '1:978035655325:ios:76f5a8193ea22be4a54a74',
    messagingSenderId: '978035655325',
    projectId: 'cooking-daddy-83353',
    storageBucket: 'cooking-daddy-83353.firebasestorage.app',
    iosClientId: '978035655325-ost7fg7mf23ila09gk1iopjtpdhvdeou.apps.googleusercontent.com',
    iosBundleId: 'com.tlam.cookingdaddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt8fOz6t2iHzHUOmCCxDwwh0pAIAeuVk4',
    appId: '1:978035655325:ios:b4ef524086596bfda54a74',
    messagingSenderId: '978035655325',
    projectId: 'cooking-daddy-83353',
    storageBucket: 'cooking-daddy-83353.firebasestorage.app',
    iosClientId: '978035655325-0f5at6toq06vbcb5q83jrd9dg6p1iod2.apps.googleusercontent.com',
    iosBundleId: 'com.example.cookingDaddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeMpPgX_ZAVDJRL9e4Jf2dsB3lJJZuvh4',
    appId: '1:978035655325:web:a27a6b30d2f0e641a54a74',
    messagingSenderId: '978035655325',
    projectId: 'cooking-daddy-83353',
    authDomain: 'cooking-daddy-83353.firebaseapp.com',
    storageBucket: 'cooking-daddy-83353.firebasestorage.app',
    measurementId: 'G-01BNEZEWY4',
  );
}
