import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'data/datasources/isar_datasource.dart';
import 'data/models/recipe.dart';
import 'firebase_options.dart';
import 'screens/auth/sign_in_screen.dart';
import 'screens/coming_soon_screen.dart';
import 'screens/dashboard_screen.dart';
import 'screens/recipe_editor.dart';
import 'screens/cooking_session.dart';
import 'screens/recipe_detail.dart';
import 'screens/settings.dart';
import 'screens/shopping_cart_screen.dart';
import 'screens/profile.dart';
import 'screens/ai_features.dart';
import 'services/notification.dart';
import 'theme/app_theme.dart';
import 'widgets/auth_gate.dart';
import 'package:easy_localization/easy_localization.dart';
import 'theme/theme_controller.dart';

void main() async {
  print('MAIN: Starting app...');
  WidgetsFlutterBinding.ensureInitialized();

  // Requires firebase_options.dart, generated by running `flutterfire
  // configure` in the project root. If that hasn't been run yet, this
  // import/call will fail to compile/run until it has.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  await IsarDatasource.initialize();

  print('MAIN: Isar initialized!');
  await EasyLocalization.ensureInitialized();

  await NotificationService.initialize();

  await ThemeController.instance.load();

  await NotificationService.initialize();
  print('MAIN: Running app...');

  runApp(
    EasyLocalization(
      supportedLocales: [Locale('en'), Locale('vi')],
      path: 'assets/translations',
      fallbackLocale: Locale('en'),
      child: CookingDaddyApp(),
    ),
  );
}

class CookingDaddyApp extends StatelessWidget {
  const CookingDaddyApp({super.key});
  // final RecipeRepository _repository = RecipeRepository();

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: ThemeController.instance,
      builder: (context, _) {
        return MaterialApp(
          title: 'Cooking Daddy',
          localizationsDelegates: context.localizationDelegates,
          supportedLocales: context.supportedLocales,
          locale: context.locale,
          debugShowCheckedModeBanner: false,
          theme: AppTheme.light(),
          initialRoute: '/home',
          routes: {
            // '/home' is the app's real entry point now — it gates on auth
            // state instead of jumping straight to MainShell.
            '/home': (context) => AuthGate(),
            '/signIn': (context) => const SignInScreen(),
            '/dashboard': (context) => const DashboardScreen(),
            '/recipeEditor': (context) {
              final recipe =
                  ModalRoute.of(context)?.settings.arguments as Recipe?;
              return RecipeEditorScreen(recipe: recipe);
            },
            '/recipeDetail': (context) => RecipeDetailScreen(
              recipeId: ModalRoute.of(context)!.settings.arguments as int,
            ),
            '/cookingSession': (context) => CookingSessionScreen(
              recipe: ModalRoute.of(context)!.settings.arguments as Recipe,
            ),
            '/settings': (context) => const SettingsScreen(),
            '/profile': (context) => const ProfileScreen(),
            '/aiFeatures': (context) => AIFeaturesScreen(),
            // Not built yet — these route to honest "coming soon" placeholders
            // rather than 404ing, so the app doesn't crash if something links
            // to them ahead of the actual feature being built.
            '/shopping': (context) =>
                const Scaffold(body: ShoppingCartScreen()),
            '/favorites': (context) => const ComingSoonScreen(
              icon: Icons.favorite_border,
              title: 'Yêu thích',
              message: 'Tính năng công thức yêu thích đang được xây dựng.',
              showAppBar: true,
            ),
            '/video': (context) => const ComingSoonScreen(
              icon: Icons.play_circle_outline,
              title: 'Video',
              message: 'Tính năng video hướng dẫn đang được xây dựng.',
              showAppBar: true,
            ),
            '/scaleRecipe': (context) => const ComingSoonScreen(
              icon: Icons.balance_outlined,
              title: 'Scale công thức',
              message:
                  'Màn hình scale công thức riêng đang được xây dựng — '
                  'hiện tại việc scale nằm trong màn hình chi tiết công thức.',
              showAppBar: true,
            ),
          },
        );
      },
    );
  }
}
